#!/usr/bin/env sh

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <CMD> <ID>"
    exit 1
fi

CMD="$1"
ID="$2"

set -x

./send_hot.py -f 452900000 -a 2000000 -c "$CMD" -u "$ID" -t i8c | hackrf_transfer -f 452900000 -s 2000000 -x 30 -t - 
