#define PROFILE_MAGIC_BASE 0x2101F000
#define PROFILE_MAGIC_NAME_SIZE 0x40

#define PROFILE_MAGIC_NAME_START (PROFILE_MAGIC_BASE + 0)
#define PROFILE_MAGIC_NAME_END                                                 \
  (PROFILE_MAGIC_NAME_START + PROFILE_MAGIC_NAME_SIZE)
#define PROFILE_MAGIC_CONTROL (PROFILE_MAGIC_NAME_END)
#define PROFILE_MAGIC_END (PROFILE_MAGIC_CONTROL + 4)